name: dimelo
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bedtools=2.30.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng
  - libgomp=9.3.0
  - libstdcxx-ng
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.2
  - python=3.7.11
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - attrs==21.4.0
    - babel==2.9.1
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - cython==0.29.27
    - docutils==0.17.1
    - idna==3.3
    - imagesize==1.3.0
    - importlib-metadata==4.11.1
    - iniconfig==1.1.1
    - jinja2==3.0.3
    - joblib==1.0.1
    - kaleido==0.2.1
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - natsort==8.1.0
    - ncls==0.0.64
    - numpy==1.20.3
    - packaging==21.3
    - pandas==1.3.2
    - pillow==9.0.1
    - plotly==4.14.3
    - pluggy==0.13.1
    - psutil==5.8.0
    - py==1.11.0
    - pybedtools==0.8.1
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyranges==0.0.104
    - pyrle==0.0.34
    - pysam==0.18.0
    - pytest==6.2.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.27.1
    - retrying==1.3.3
    - scipy==1.7.3
    - seaborn==0.11.2
    - six==1.16.0
    - snowballstemmer==2.2.0
    - sorted-nearest==0.0.33
    - sphinx==4.4.0
    - sphinx-argparse-cli==1.9.0
    - sphinx-gallery==0.10.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sphinx-rtd-theme==1.0.0
    - tabulate==0.8.9
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - zipp==3.7.0
