name: dimelo

on: 
  workflow_dispatch:  # Allows manual trigger of the workflow
  pull_request:  # Trigger by default on PR opened, reopened, or synchronized (commits pushed to PR)

jobs:
  platform_matrix:  # Run the tests on each supported platform
    strategy:
      matrix:
        platform:  # Define the platform tag and the file name of the appropriate miniconda install script
          - os: ubuntu-latest
            miniconda: Miniconda3-latest-Linux-x86_64.sh
          - os: macos-latest
            miniconda: Miniconda3-latest-MacOSX-x86_64.sh
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda and run pytest
        run: |
          # Install Miniconda if not available on the runner
          wget https://repo.anaconda.com/miniconda/${{ matrix.platform.miniconda }} -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source $HOME/miniconda/etc/profile.d/conda.sh
          
          # Create conda environment from environment.yml
          conda env create -f environment.yml
          
          # Activate the environment
          conda activate $(head -n 1 environment.yml | cut -d' ' -f2)
          
          # Install pip dependencies and the package itself
          pip install .
          
          # Additional testing dependencies not covered in environment.yml
          conda install pytest

          # Make sure everything is installed correctly
          conda list

          # Run pytest
          pytest
